[package]
name = "config_plugin"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
gun_plugin = { workspace = true }
